name: troupe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  google_nav_bar: ^5.0.3
  flutter_icons: ^1.1.0
  rating_dialog: ^2.0.0
  alert: ^1.0.1
  any_link_preview: ^1.0.7
  path_provider: ^2.0.1
  ndialog: ^4.0.1
  screenshot: ^0.3.0
  google_sign_in: ^4.5.6
  share: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
